import { getCloudflareContext } from "@opennextjs/cloudflare";
import { NextResponse } from "next/server";
import { getSession } from "../../../../lib/files/auth/session";
import { findUserById, getUserPermissions } from "../../../../lib/files/auth/repository";
import type { AuthDatabase, AuthSessionStore } from "../../../../lib/files/auth/types";
import { CANONICAL } from "../../../../lib/config/canonical";

export const runtime = "edge";
export const dynamic = "force-dynamic";
const HEADERS={"Cache-Control":"no-store, max-age=0","Content-Type":"application/json; charset=utf-8","X-Content-Type-Options":"nosniff","Referrer-Policy":"no-referrer"};
const FORMATS={"1080x1080":[1080,1080],"1080x1350":[1080,1350],"1080x1920":[1080,1920],"1200x630":[1200,630],"A4":[2480,3508]} as const;
type Env={DB?:AuthDatabase;SESSION_STORE?:AuthSessionStore;SESSION_COOKIE_NAME?:string};
type Body={entityType?:unknown;entityId?:unknown;format?:unknown;locale?:unknown};
type EventRecord={entityType:string;entityId:string;titleBn:string;titleEn:string|null;date:string;time:string;location:string;destinationPath:string;sourceIds:string[];summary:string|null};
function traceId(request:Request){const v=request.headers.get("x-request-id")?.trim();return v&&v.length<=128?v:crypto.randomUUID();}
function out(status:number,trace:string,data:unknown,error?:{code:string;message:string}){return NextResponse.json(error?{ok:false,error,meta:{traceId:trace}}:{ok:true,data,meta:{traceId:trace}},{status,headers:HEADERS});}
function cookie(request:Request,name:string){const raw=request.headers.get("cookie");if(!raw)return null;const m=raw.split(";").map((x)=>x.trim()).find((x)=>x.startsWith(`${name}=`));return m?decodeURIComponent(m.slice(name.length+1)):null;}
async function parse(request:Request):Promise<Body|null>{const raw=await request.text();if(raw.length>4096)return null;try{const p:unknown=JSON.parse(raw);return p&&typeof p==="object"&&!Array.isArray(p)?p as Body:null;}catch{return null;}}
function text(v:unknown,max:number){if(typeof v!=="string")return null;const s=v.trim();return s&&s.length<=max?s:null;}
async function actorId(env:Env,request:Request):Promise<string|null>{if(!env.DB||!env.SESSION_STORE)return null;const token=cookie(request,env.SESSION_COOKIE_NAME?.trim()||"raksha_kali_session");if(!token)return null;const session=await getSession(env.DB,env.SESSION_STORE,token);if(!session)return null;const user=await findUserById(env.DB,session.userId);if(!user||user.status!=="ACTIVE"||!user.personId)return null;const perms=await getUserPermissions(env.DB,user.id);if(!perms.some((p)=>p.code==="social.generate"))return null;const current=await env.DB.prepare(`SELECT cra.person_id FROM committee_role_assignments cra JOIN committee_terms ct ON ct.id=cra.committee_term_id JOIN committees c ON c.id=ct.committee_id WHERE cra.person_id=? AND cra.committee_term_id=? AND c.id=? AND cra.status='ACTIVE' AND ct.status='ACTIVE' AND c.status='ACTIVE' LIMIT 1`).bind(user.personId,CANONICAL.currentCommitteeTermId,CANONICAL.committeeId).first<{person_id:string}>();return current?user.id:null;}
function sourceIds(raw:string|null):string[]{try{const v:unknown=JSON.parse(raw??"[]");return Array.isArray(v)&&v.every((x)=>typeof x==="string")?v:[];}catch{return[];}}
function svg(record:EventRecord,width:number,height:number,locale:string,siteOrigin:string){const title=locale.startsWith("en")?record.titleEn??record.titleBn:record.titleBn;const escape=(v:string)=>v.replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;").replace(/"/g,"&quot;");const path=`${record.destinationPath}`;const qr=`${new URL(path,siteOrigin).toString()}`;return `<svg xmlns="http://www.w3.org/2000/svg" width="${width}" height="${height}" viewBox="0 0 ${width} ${height}"><title>${escape(title)}</title><desc>Official-origin social card for ${escape(record.entityId)}</desc><rect width="100%" height="100%" fill="#FBF4E6"/><text x="7%" y="16%" font-family="serif" font-size="${Math.max(42,Math.floor(width/16))}" font-weight="700" fill="#24201D">${escape(title)}</text><text x="7%" y="29%" font-family="sans-serif" font-size="${Math.max(22,Math.floor(width/32))}" fill="#8F241C">${escape(record.date)}${record.time?` · ${escape(record.time)}`:""}</text><text x="7%" y="39%" font-family="sans-serif" font-size="${Math.max(20,Math.floor(width/40))}" fill="#24201D">${escape(record.location)}</text><text x="7%" y="72%" font-family="sans-serif" font-size="${Math.max(20,Math.floor(width/40))}" fill="#24201D">${escape(record.summary??"")}</text><rect x="7%" y="84%" width="86%" height="9%" rx="18" fill="#8F241C"/><text x="50%" y="90%" text-anchor="middle" font-family="sans-serif" font-size="${Math.max(20,Math.floor(width/42))}" fill="#FBF4E6">Official · Sri Sri Maa Raksha Kali Mandir · ${escape(qr)}</text></svg>`;}
export async function POST(request:Request):Promise<NextResponse>{const trace=traceId(request);const env=getCloudflareContext().env as unknown as Env;if(!env.DB)return out(503,trace,null,{code:"DEPENDENCY_FAILURE",message:"Social card ব্যবস্থা এখন প্রস্তুত নয়।"});const actor=await actorId(env,request);if(!actor)return out(403,trace,null,{code:"FORBIDDEN",message:"Social card generate করার অনুমতি নেই।"});const body=await parse(request);const entityType=text(body?.entityType,32)?.toUpperCase();const entityId=text(body?.entityId,128);const format=text(body?.format,16) as keyof typeof FORMATS|null;const locale=text(body?.locale,8)??"bn-IN";if(!body||!entityType||!entityId||!format||!FORMATS[format]||!["bn","en","bn-IN","en-IN"].includes(locale))return out(400,trace,null,{code:"INVALID_INPUT",message:"Social card-এর তথ্য সঠিক নয়।"});
 try{let record:EventRecord|null=null;
 if(entityType==="AMAVASYA"){const row=await env.DB.prepare(`SELECT a.id,a.display_name_bn,a.display_name_en,a.gregorian_date,a.tithi_start,a.source_ids_json,a.status,a.verification_status,l.address_bn,sd.canonical_path FROM amavasyas a JOIN search_documents sd ON sd.entity_id=a.id AND sd.entity_type='AMAVASYA' AND sd.audience_scope='PUBLIC' AND sd.publication_status='PUBLISHED' AND sd.verification_status='VERIFIED' LEFT JOIN temple_locations l ON l.id=? AND l.status='ACTIVE' WHERE a.id=? AND a.status IN ('APPROVED','PUBLISHED') AND a.verification_status='VERIFIED' LIMIT 1`).bind(CANONICAL.locationId,entityId).first<{id:string;display_name_bn:string;display_name_en:string;gregorian_date:string;tithi_start:string;source_ids_json:string;status:string;verification_status:string;address_bn:string|null;canonical_path:string|null}>();if(row&&row.canonical_path)record={entityType,entityId:row.id,titleBn:row.display_name_bn,titleEn:row.display_name_en,date:row.gregorian_date,time:row.tithi_start.slice(11,16),location:row.address_bn??"",destinationPath:row.canonical_path,sourceIds:sourceIds(row.source_ids_json),summary:"প্রতি অমাবস্যায় পূজা"};}
 else if(entityType==="FESTIVAL"){const row=await env.DB.prepare(`SELECT fe.id,fe.display_name_bn,fe.display_name_en,fe.gregorian_start,fe.source_ids_json,fe.status,fe.verification_status,f.id AS festival_id,sd.canonical_path,l.address_bn FROM festival_editions fe JOIN festivals f ON f.id=fe.festival_id JOIN search_documents sd ON sd.entity_id=fe.id AND sd.entity_type='FESTIVALEDITION' AND sd.audience_scope='PUBLIC' AND sd.publication_status='PUBLISHED' AND sd.verification_status='VERIFIED' LEFT JOIN temple_locations l ON l.id=? AND l.status='ACTIVE' WHERE (fe.id=? OR f.id=?) AND fe.status='PUBLISHED' AND fe.verification_status='VERIFIED' LIMIT 1`).bind(entityId,entityId).first<{id:string;display_name_bn:string|null;display_name_en:string|null;gregorian_start:string|null;source_ids_json:string;status:string;verification_status:string;festival_id:string;canonical_path:string|null;address_bn:string|null}>();if(row&&row.gregorian_start&&row.canonical_path&&row.address_bn)record={entityType,entityId:row.id,titleBn:row.display_name_bn??"",titleEn:row.display_name_en,date:row.gregorian_start.slice(0,10),time:row.gregorian_start.length>10?row.gregorian_start.slice(11,16):"",location:row.address_bn,destinationPath:row.canonical_path,sourceIds:sourceIds(row.source_ids_json),summary:null};}
 if(!record)return out(404,trace,null,{code:"APPROVED_EVENT_NOT_FOUND",message:"এই ID-এর অনুমোদিত public event record পাওয়া যায়নি।"});
 if(!record.titleBn||!record.date||!record.location||!record.destinationPath)return out(409,trace,null,{code:"INCOMPLETE_CANONICAL_RECORD",message:"Canonical event record-এ social card-এর প্রয়োজনীয় তথ্য অসম্পূর্ণ।"});
 const [width,height]=FORMATS[format];const siteOrigin=new URL(request.url).origin;const imageSvg=svg(record,width,height,locale,siteOrigin);return out(200,trace,{card:{format,width,height,family:entityType,locale,title:locale.startsWith("en")?(record.titleEn??record.titleBn):record.titleBn,date:record.date,time:record.time||null,location:record.location,destinationPath:record.destinationPath,qrDestination:new URL(record.destinationPath,siteOrigin).toString(),officialOrigin:true,imageMime:"image/svg+xml",imageSvg},provenance:{entityType,entityId,sourceIds:record.sourceIds,generatedFrom:"APPROVED_CANONICAL_EVENT"}});
 }catch{return out(500,trace,null,{code:"INTERNAL_FAILURE",message:"Social card তৈরি করা যায়নি।"});}}
