import { getCloudflareContext } from "@opennextjs/cloudflare";
import { NextResponse } from "next/server";
import { CANONICAL } from "../../../lib/config/canonical";
import type { D1Like } from "../../../lib/db/client";

export const runtime = "edge";
export const dynamic = "force-dynamic";

type Env = { DB?: D1Like; AI_API_URL?: string; AI_API_KEY?: string; AI_MODEL?: string };
type Body = { message?: unknown; locale?: unknown; currentPath?: unknown; conversation?: unknown };
type SearchRow = { id:string; entity_type:string; entity_id:string; locale:string; title:string; summary:string|null; body:string; canonical_path:string|null; source_ids_json:string; revision_id:string|null; version:number };
const HEADERS={"Cache-Control":"no-store, max-age=0","Content-Type":"application/json; charset=utf-8","X-Content-Type-Options":"nosniff","Referrer-Policy":"no-referrer","Vary":"Accept-Language"};
const MAX_BODY=16*1024, MAX_MESSAGE=4000;
const SYSTEM="You are Bhairava AI, a grounded temple information and assistance interface. You are not the deity and not a divine authority. Do not claim supernatural authority. Use only supplied canonical context for temple facts. If context is insufficient, say so.";
function trace(r:Request){const v=r.headers.get("x-request-id")?.trim();return v&&v.length<=128?v:crypto.randomUUID();}
function out(status:number,t:string,data:unknown,error?:{code:string;message:string}){return NextResponse.json(error?{ok:false,error,meta:{traceId:t}}:{ok:true,data,meta:{traceId:t}},{status,headers:HEADERS});}
async function bodyOf(r:Request):Promise<Body|null>{const len=r.headers.get("content-length");if(len&&(!/^\d+$/.test(len)||Number(len)>MAX_BODY))return null;const raw=await r.text();if(new TextEncoder().encode(raw).byteLength>MAX_BODY)return null;try{const v:unknown=JSON.parse(raw);return v&&typeof v==="object"&&!Array.isArray(v)?v as Body:null;}catch{return null;}}
function text(v:unknown,max:number){if(typeof v!=="string")return null;const s=v.trim();return s&&s.length<=max?s:null;}
function locale(v:unknown){return text(v,12)?.toLowerCase().startsWith("bn")?"bn":"en" as const;}
function safeArray(v:string){try{const a:unknown=JSON.parse(v);return Array.isArray(a)?a.filter((x):x is string=>typeof x==="string").slice(0,8):[];}catch{return [];}}
function score(q:string,row:SearchRow){const hay=`${row.title} ${row.summary??""} ${row.body}`.toLocaleLowerCase();return q.toLocaleLowerCase().split(/\s+/).filter(x=>x.length>1).reduce((n,t)=>n+(hay.includes(t)?(row.title.toLocaleLowerCase().includes(t)?3:1):0),0);}
async function ground(db:D1Like,q:string,loc:"bn"|"en"){const rows=await db.prepare(`SELECT id,entity_type,entity_id,locale,title,summary,body,canonical_path,source_ids_json,revision_id,version FROM search_documents WHERE audience_scope='PUBLIC' AND publication_status='PUBLISHED' AND verification_status='VERIFIED' AND locale IN (?,?) ORDER BY updated_at DESC LIMIT 50`).bind(loc,loc==="bn"?"bn-IN":"en-IN").all<SearchRow>();return rows.results.filter(r=>`${r.title} ${r.summary??""} ${r.body}`.toLocaleLowerCase().includes(q.toLocaleLowerCase().slice(0,120))).sort((a,b)=>score(q,b)-score(q,a)).slice(0,8);}
async function provider(env:Env,message:string,loc:"bn"|"en",rows:SearchRow[],path:string|null){const url=env.AI_API_URL?.trim(),key=env.AI_API_KEY?.trim(),model=env.AI_MODEL?.trim();if(!url||!key||!model)return null;let endpoint:URL;try{endpoint=new URL(url);if(endpoint.protocol!=="https:")return null;}catch{return null;}const context=rows.map(r=>`[${r.entity_type}:${r.entity_id}] ${r.title}\n${r.summary??r.body}`).join("\n\n").slice(0,12000);const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),12000);try{const res=await fetch(endpoint.toString(),{method:"POST",headers:{Authorization:`Bearer ${key}`,"Content-Type":"application/json"},body:JSON.stringify({model,input:[{role:"system",content:SYSTEM},{role:"user",content:`Language: ${loc}\nCurrent page: ${path??"(unknown)"}\nCanonical grounding:\n${context||"(none)"}\n\nQuestion:\n${message}`}]}),signal:controller.signal});if(!res.ok)return null;const payload:unknown=await res.json();if(!payload||typeof payload!=="object")return null;const p=payload as {output_text?:unknown};return typeof p.output_text==="string"&&p.output_text.trim()?p.output_text.trim():null;}catch{return null;}finally{clearTimeout(timer);}}
export async function POST(request:Request):Promise<NextResponse>{const t=trace(request),env=getCloudflareContext().env as unknown as Env;if(!env.DB)return out(503,t,null,{code:"DEPENDENCY_FAILURE",message:"AI তথ্যভান্ডার এখন উপলব্ধ নয়।"});const body=await bodyOf(request),message=body?text(body.message,MAX_MESSAGE):null,path=body?.currentPath==null?null:text(body.currentPath,512),loc=locale(body?.locale);if(!body||!message)return out(400,t,null,{code:"INVALID_INPUT",message:"প্রশ্নটি সঠিকভাবে দিন।"});try{const rows=await ground(env.DB,message,loc);const generated=await provider(env,message,loc,rows,path);const answer=generated??(rows.length?rows[0].title+": "+(rows[0].summary??rows[0].body).slice(0,800):(loc==="bn"?"এই প্রশ্নের জন্য অনুমোদিত বর্তমান মন্দির তথ্য পাওয়া যায়নি।":"No approved current temple information was found for this question."));return out(200,t,{product:loc==="bn"?CANONICAL.aiProductNameBn:CANONICAL.aiProductName,identityNotice:loc==="bn"?"ভৈরব AI মন্দিরের অনুমোদিত তথ্যের সহায়ক; এটি দেবতা বা দৈব কর্তৃপক্ষ নয়।":"Bhairava AI is an assistance interface over approved temple information; it is not the deity or a divine authority.",answer,grounded:rows.length>0,sources:rows.map(r=>({entityType:r.entity_type,entityId:r.entity_id,title:r.title,canonicalPath:r.canonical_path,sourceIds:safeArray(r.source_ids_json),revisionId:r.revision_id,version:r.version}))});}catch{return out(503,t,null,{code:"DEPENDENCY_FAILURE",message:"AI উত্তর প্রস্তুত করা যাচ্ছে না।"});}}
