import { AmavasyaTithi, GalleryItem, PoojaTiming, PresetAmount } from "@/types";

export const SITE_CONFIG = {
  name: "শ্রী শ্রী মা রক্ষা কালী মন্দির",
  englishName: "Sri Sri Maa Raksha Kali Mandir",
  committeeName: "শ্রী শ্রী মা রক্ষা কালী পূজা কমিটি ও সকল গ্রামবাসী",
  tagline: "গ্রামের জাগ্রত অধিষ্ঠাত্রী দেবী — অভয়, শান্তি ও সার্বিক সুরক্ষার পরম ধাম",
  shloka: "ওঁ ক্রীং কাল্যৈ নমঃ",
  canonicalUrl: "https://maarakshakali.pages.dev",

  location: {
    spot: "সাহাপুর বটতলা মোড়",
    village: "সাহাপুর (Sahapur)",
    postOffice: "লহণ্ডা (Lahanda)",
    policeStation: "রায়গঞ্জ (Raiganj)",
    district: "উত্তর দিনাজপুর (Uttar Dinajpur)",
    state: "পশ্চিমবঙ্গ (West Bengal)",
    pincode: "733130",
    pincodeBn: "৭৩৩১৩০",
    fullAddressBn: "সাহাপুর বটতলা মোড়, গ্রাম: সাহাপুর, ডাকঘর: লহণ্ডা, রায়গঞ্জ, উত্তর দিনাজপুর, পশ্চিমবঙ্গ - ৭৩৩১৩০",
    mapsUrl: "https://maps.app.goo.gl/AwerSG1peoGm2gUx9",
  },

  whatsapp: {
    groupLink: "https://chat.whatsapp.com/IRoYErTIKYF4Qr2bPl8FMX",
    buttonText: "হোয়াটসঅ্যাপ গ্রুপে যুক্ত হোন",
    noticeText: "মন্দির নির্মাণ, নিত্য পূজা এবং গ্রামের সার্বিক সামাজিক ঐক্যের উদ্যোগে সক্রিয় অংশ নিতে আমাদের অফিসিয়াল হোয়াটসঅ্যাপ গ্রুপে যোগ দিন।",
  },

  vpa: process.env.NEXT_PUBLIC_TEMPLE_VPA || "7583992377@okbizaxis",
  payeeName: "Sri Sri Raksha Kali Mandir",
  transactionNote: "শ্রী শ্রী রক্ষা কালী মন্দির প্রণামী",
  minContribution: 11,

  presetAmounts: [
    { bn: "₹৫১", val: 51 },
    { bn: "₹১০১", val: 101 },
    { bn: "₹৫০১", val: 501 },
    { bn: "₹১০০১", val: 1001 },
  ] as PresetAmount[],

  navLinks: [
    { label: "মূল পাতা", href: "#hero" },
    { label: "প্রতিষ্ঠা ও মাহাত্ম্য", href: "#legend" },
    { label: "পঞ্জিকা তিথি", href: "#panjika" },
    { label: "নিত্য নির্ঘণ্ট", href: "#darshan" },
    { label: "চিত্রশালা", href: "#gallery" },
    { label: "অনলাইন সেবা/প্রণামী", href: "#seva" },
    { label: "যোগাযোগ ও অবস্থান", href: "#location" },
  ],

  timings: [
    { name: "মঙ্গলারতি ও প্রাতঃকালীন পূজা", time: "ভোর ০৬:০০" },
    { name: "নিত্য ভোগরাগ ও মধ্যাহ্ন আরতি", time: "দুপুর ১২:০০" },
    { name: "অপরাহ্ন দ্বার উন্মোচন", time: "বিকাল ০৪:৩০" },
    { name: "সন্ধ্যা আরতি ও মাতৃবন্দনা", time: "সন্ধ্যা ০৭:০০" },
    { name: "শয়ন আরতি ও গর্ভগৃহ সংবরণ", time: "রাত ০৮:৪৫" },
  ] as PoojaTiming[],

  amavasyaList: [
    {
      id: "kaushiki-1433",
      name: "কৌশিকী অমাবস্যা (ভাদ্র অমাবস্যা)",
      bengaliMonth: "২৪ ভাদ্র ১৪৩৩",
      englishDate: "১০ সেপ্টেম্বর ২০২৬, বৃহস্পতিবার",
      starts: "১০ সেপ্টেম্বর, সকাল ১০:৩৩ মিনিট",
      ends: "১১ সেপ্টেম্বর, সকাল ০৮:৫৬ মিনিট",
      isSpecial: true,
      significance: "মহামায়ার কৌশিকী রূপ ধারণ ও অসুর বিনাশের পরম পবিত্র তিথি। বিশেষ হোমযজ্ঞ ও পুষ্পাঞ্জলি অনুষ্ঠিত হয়।",
    },
    {
      id: "mahalaya-1433",
      name: "মহালয়া অমাবস্যা (সর্বপিতৃ অমাবস্যা)",
      bengaliMonth: "২৩ আশ্বিন ১৪৩৩",
      englishDate: "১০ অক্টোবর ২০২৬, শনিবার",
      starts: "০৯ অক্টোবর, রাত ১১:৪৫ মিনিট",
      ends: "১০ অক্টোবর, রাত ০৯:১২ মিনিট",
      isSpecial: true,
      significance: "পিতৃতর্পণ ও দেবীপক্ষের পুণ্য সূচনা। ভোর থেকেই সাহাপুর বটতলা মোড় মন্দিরে শ্রীশ্রীচণ্ডীপাঠ ও বিশেষ বন্দনা অনুষ্ঠিত হয়।",
    },
    {
      id: "shyama-1433",
      name: "দীপান্বিতা শ্যামাপূজা (কার্তিকী অমাবস্যা)",
      bengaliMonth: "২১ কার্তিক ১৪৩৩",
      englishDate: "০৮ নভেম্বর ২০২৬, রবিবার",
      starts: "০৮ নভেম্বর, দুপুর ০১:২২ মিনিট",
      ends: "০৯ নভেম্বর, সকাল ১১:০৮ মিনিট",
      isSpecial: true,
      significance: "মন্দিরের প্রধান বাৎসরিক মহোৎসব। নিশীথকালে মহানিশা পূজা, ১০৮ রক্তজবা ও অন্নকূট মহোৎসব।",
    },
    {
      id: "agrahayan-1433",
      name: "অগ্রহায়ণ অমাবস্যা",
      bengaliMonth: "২২ অগ্রহায়ণ ১৪৩৩",
      englishDate: "০৮ ডিসেম্বর ২০২৬, মঙ্গলবার",
      starts: "০৮ ডিসেম্বর, ভোর ০৩:১৫ মিনিট",
      ends: "০৯ ডিসেম্বর, রাত ১২:৪০ মিনিট",
      isSpecial: false,
      significance: "নবধান্যের পায়েস সহযোগে মায়ের বিশেষ ভোগ নিবেদন ও আরতি।",
    },
    {
      id: "poush-1433",
      name: "পৌষ অমাবস্যা (বকুল অমাবস্যা)",
      bengaliMonth: "২২ পৌষ ১৪৩৩",
      englishDate: "০৬ জানুয়ারি ২০২৭, বুধবার",
      starts: "০৬ জানুয়ারি, দুপুর ০২:০৫ মিনিট",
      ends: "০৭ জানুয়ারি, সকাল ১১:৩০ মিনিট",
      isSpecial: false,
      significance: "শীতকালীন বিশেষ ভোগ ও ভক্তদের মাঝে প্রসাদ বিতরণ।",
    },
    {
      id: "maghi-1433",
      name: "মাঘী রটন্তী কালীপূজা (মাঘ অমাবস্যা)",
      bengaliMonth: "২১ মাঘ ১৪৩৩",
      englishDate: "০৫ ফেব্রুয়ারি ২০২৭, শুক্রবার",
      starts: "০৪ ফেব্রুয়ারি, রাত ১০:৫০ মিনিট",
      ends: "০৫ ফেব্রুয়ারি, রাত ০৮:২০ মিনিট",
      isSpecial: true,
      significance: "রটন্তী চতুর্দশী যুক্ত বিশেষ কালী আরাধনা ও সংকীর্তন মহোৎসব।",
    },
  ] as AmavasyaTithi[],

  galleryItems: [
    {
      id: "darshan-1",
      title: "মায়ের অমাবস্যা মহাদর্শন",
      category: "বিগ্রহ",
      imageUrl: "/images/darshan-kali.svg",
      caption: "সাহাপুর বটতলা মোড় মন্দিরে অমাবস্যা নিশীথে রক্তজবা ও স্বর্ণালঙ্কারে ভূষিত চিন্ময় রূপ।",
    },
    {
      id: "aarti-2",
      title: "সন্ধ্যা পঞ্চপ্রদীপ আরতি",
      category: "আরতি",
      imageUrl: "/images/aarti.svg",
      caption: "ধূপ-ধুনো, শঙ্খধ্বনি ও কাঁসর-ঘণ্টার সম্মিলনে সান্ধ্য বন্দনা।",
    },
    {
      id: "festival-3",
      title: "বাৎসরিক উৎসব ও ভক্ত সমাগম",
      category: "উৎসব",
      imageUrl: "/images/festival.svg",
      caption: "সাহাপুর ও লহণ্ডা গ্রামবাসীর সম্মিলিত আনন্দ ও ভক্তিপূর্ণ উপস্থিতি।",
    },
    {
      id: "temple-4",
      title: "সাহাপুর বটতলা মোড় প্রাঙ্গণ",
      category: "প্রাঙ্গণ",
      imageUrl: "/images/battala.svg",
      caption: "লহণ্ডা অঞ্চলের ছায়াঘেরা ঐতিহাসিক বটবৃক্ষের আশ্রয়ে প্রতিষ্ঠিত মাতৃপীঠ।",
    },
  ] as GalleryItem[],
};
