import type { D1Like } from "../../../../lib/db/client";
import { getCloudflareContext } from "@opennextjs/cloudflare";
import { NextResponse } from "next/server";
import { getSession } from "../../../../lib/files/auth/session";
import { findUserById, getUserPermissions } from "../../../../lib/files/auth/repository";
import type { AuthDatabase, AuthSessionStore } from "../../../../lib/files/auth/types";

export const runtime = "edge";
export const dynamic = "force-dynamic";

type Env = { DB?: D1Like & AuthDatabase; SESSION_STORE?: AuthSessionStore; SESSION_COOKIE_NAME?: string };
type Row = Record<string, unknown>;

const HEADERS = { "Cache-Control":"no-store, max-age=0","Content-Type":"application/json; charset=utf-8","X-Content-Type-Options":"nosniff","Referrer-Policy":"no-referrer" };
const DENY_TABLES = new Set(["auth_sessions","auth_password_reset_tokens","users","user_roles","auth_roles","permissions","role_permissions"]);
const DEFAULT_TABLES = ["temples","temple_locations","committees","committee_terms","persons","priests","committee_roles","committee_role_orders","committee_role_assignments","sources","revisions","audit_logs","notifications","notification_subscriptions","notification_dispatches","panjika_years","panjika_days","tithis","tithi_occurrences","nakshatra_occurrences","amavasyas","festivals","festival_editions","temple_observances","documents","document_versions","document_reviews","document_state_events","document_extractions","jaba_offerings","jaba_offering_cycles","jaba_participants","jaba_submissions","jaba_duplicate_checks","music_sources","music_rights","music_tracks","music_publications","music_albums","music_playlists","music_playlist_items"];

function traceId(r:Request){const v=r.headers.get("x-request-id")?.trim();return v&&v.length<=128?v:crypto.randomUUID();}
function out(status:number,t:string,data:unknown,error?:{code:string;message:string}){return NextResponse.json(error?{ok:false,error,meta:{traceId:t}}:{ok:true,data,meta:{traceId:t}},{status,headers:HEADERS});}
function cookie(r:Request,n:string){const h=r.headers.get("cookie");if(!h)return null;const e=n.replace(/[.*+?^${}()|[\]\\]/g,"\\$&");const m=h.match(new RegExp(`(?:^|;\\s*)${e}=([^;]*)`));return m?.[1]?decodeURIComponent(m[1]):null;}

async function auth(r:Request):Promise<{env:Env;userId:string}|NextResponse>{const env=getCloudflareContext().env as unknown as Env;const t=traceId(r);if(!env.DB||!env.SESSION_STORE)return out(503,t,null,{code:"DEPENDENCY_FAILURE",message:"প্রশাসনিক সেবা এখন উপলব্ধ নয়।"});const s=cookie(r,env.SESSION_COOKIE_NAME||"raksha_kali_session");if(!s)return out(401,t,null,{code:"SESSION_INVALID",message:"প্রশাসনিক লগইন প্রয়োজন।"});try{const sess=await getSession(env.DB,env.SESSION_STORE,s);if(!sess)return out(401,t,null,{code:"SESSION_INVALID",message:"আপনার প্রশাসনিক সেশন আর বৈধ নয়।"});const u=await findUserById(env.DB,sess.userId);if(!u||u.status!=="ACTIVE"||!u.personId)return out(403,t,null,{code:"FORBIDDEN",message:"এই কাজের অনুমতি নেই।"});const p=await getUserPermissions(env.DB,u.id);if(!p.some(x=>x.code==="export.run"||x.code==="audit.export"))return out(403,t,null,{code:"FORBIDDEN",message:"ডেটা export করার অনুমতি নেই।"});return {env,userId:u.id};}catch{return out(503,t,null,{code:"DEPENDENCY_FAILURE",message:"প্রশাসনিক অনুমতি যাচাই করা যায়নি।"});}}

function qid(name:string){if(!/^[A-Za-z_][A-Za-z0-9_]*$/.test(name))throw new Error("INVALID_IDENTIFIER");return `"${name.replace(/"/g,'""')}"`;}
function normalizeTables(raw:string|null):string[]{const names=(raw?raw.split(","):DEFAULT_TABLES).map(x=>x.trim()).filter(Boolean);if(!names.length||names.length>80)throw new Error("INVALID_TABLE_SET");for(const n of names)if(!DEFAULT_TABLES.includes(n)||DENY_TABLES.has(n))throw new Error("TABLE_NOT_EXPORTABLE");return [...new Set(names)].sort();}
function sortRows(rows:Row[]){return rows.slice().sort((a,b)=>String(a.id??JSON.stringify(a)).localeCompare(String(b.id??JSON.stringify(b))));}

export async function GET(request:Request):Promise<NextResponse>{const t=traceId(request);const principal=await auth(request);if(principal instanceof NextResponse)return principal;try{const url=new URL(request.url);const format=(url.searchParams.get("format")||"json").toLowerCase();if(format!=="json"&&format!=="sql")return out(400,t,null,{code:"INVALID_FORMAT",message:"শুধু json অথবা sql export করা যায়।"});const tables=normalizeTables(url.searchParams.get("tables"));const exported:{table:string;columns:string[];rows:Row[]}[]=[];for(const table of tables){const cols=await principal.env.DB!.prepare(`PRAGMA table_info(${qid(table)})`).all<{name:string}>();const columnNames=cols.results.map(x=>x.name);if(!columnNames.length)throw new Error("TABLE_NOT_FOUND");const result=await principal.env.DB!.prepare(`SELECT ${columnNames.map(qid).join(",")} FROM ${qid(table)}`).all<Row>();exported.push({table,columns:columnNames,rows:sortRows(result.results)});}const manifest={schemaVersion:1,exportedAt:new Date().toISOString(),timezone:"Asia/Kolkata",tables:exported.map(x=>({table:x.table,rowCount:x.rows.length})),scope:"ADMIN_CANONICAL_EXPORT"};await principal.env.DB!.prepare(`INSERT INTO audit_logs (id,actor_user_id,action,entity_type,entity_id,result,reason_private,request_id,occurred_at,created_at) VALUES (?,?,?,?,?,?,?,?,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP)`).bind(crypto.randomUUID(),principal.userId,"EXPORT","SYSTEM","ADMIN_EXPORT","SUCCESS","authorized canonical export",t).run();if(format==="json")return out(200,t,{manifest,tables:exported});const lines:[string]=["-- Raksha Kali Mandir canonical administrative export; generated from D1; no credentials/session secrets included."];for(const table of exported){for(const row of table.rows){const values=table.columns.map(c=>{const v=row[c];if(v===null)return "NULL";if(typeof v==="number"||typeof v==="bigint")return String(v);return `'${String(v).replace(/'/g,"''")}'`;}).join(",");lines.push(`INSERT INTO ${qid(table.table)} (${table.columns.map(qid).join(",")}) VALUES (${values});`);}}return new NextResponse(lines.join("\n")+"\n",{status:200,headers:{...HEADERS,"Content-Type":"application/sql; charset=utf-8","Content-Disposition":`attachment; filename="raksha-kali-export-${new Date().toISOString().slice(0,10)}.sql"`}});}catch(e){const code=e instanceof Error?e.message:"EXPORT_FAILED";if(code==="TABLE_NOT_EXPORTABLE"||code==="INVALID_TABLE_SET"||code==="TABLE_NOT_FOUND")return out(400,t,null,{code,message:"অনুরোধকৃত export scope বৈধ নয়।"});return out(503,t,null,{code:"EXPORT_FAILED",message:"ডেটা export করা যায়নি।"});}}
