import { getCloudflareContext } from "@opennextjs/cloudflare";
import { NextResponse } from "next/server";
import { getSession } from "../../../../lib/files/auth/session";
import { findUserById, getUserPermissions } from "../../../../lib/files/auth/repository";
import type { AuthDatabase, AuthSessionStore } from "../../../../lib/files/auth/types";
import { CANONICAL } from "../../../../lib/config/canonical";

export const runtime = "edge";
export const dynamic = "force-dynamic";

type Env = { DB?: AuthDatabase; SESSION_STORE?: AuthSessionStore; SESSION_COOKIE_NAME?: string };
type Body = { ticketId?: unknown; queueCode?: unknown; assignedUserId?: unknown; assignedRoleId?: unknown; expectedVersion?: unknown; reasonCode?: unknown };
const QUEUE_BY_CATEGORY: Record<string,string> = { FINANCE:"FINANCE", PUJA:"PUJA", GRIEVANCE:"GOVERNANCE", GENERAL:"GENERAL" };
const H={"Cache-Control":"no-store, max-age=0","Content-Type":"application/json; charset=utf-8","X-Content-Type-Options":"nosniff","Referrer-Policy":"no-referrer"};
function trace(request:Request){const v=request.headers.get("x-request-id")?.trim();return v&&v.length<=128?v:crypto.randomUUID();}
function out(status:number,t:string,data:unknown,error?:{code:string;message:string}){return NextResponse.json(error?{ok:false,error,meta:{traceId:t}}:{ok:true,data,meta:{traceId:t}},{status,headers:H});}
function cookie(request:Request,name:string){const h=request.headers.get("cookie");if(!h)return null;const m=h.match(new RegExp(`(?:^|;\\s*)${name.replace(/[.*+?^${}()|[\\]\\]/g,"\\$&")}=([^;]*)`));return m?.[1]?decodeURIComponent(m[1]):null;}
async function parse(request:Request):Promise<Body|null>{const len=request.headers.get("content-length");if(len&&(!/^\d+$/.test(len)||Number(len)>8192))return null;const text=await request.text();if(new TextEncoder().encode(text).byteLength>8192)return null;try{const v:unknown=JSON.parse(text);return v&&typeof v==="object"&&!Array.isArray(v)?v as Body:null;}catch{return null;}}
function s(v:unknown,max:number){if(typeof v!=="string")return null;const x=v.trim();return x&&x.length<=max?x:null;}
async function auth(env:Env,request:Request):Promise<{userId:string}|NextResponse>{if(!env.DB||!env.SESSION_STORE)return out(503,trace(request),null,{code:"DEPENDENCY_FAILURE",message:"Assignment ব্যবস্থা এখন প্রস্তুত নয়।"});const token=cookie(request,env.SESSION_COOKIE_NAME||"raksha_kali_session");if(!token)return out(401,trace(request),null,{code:"SESSION_INVALID",message:"অনুগ্রহ করে প্রশাসনিক অ্যাকাউন্ট দিয়ে লগইন করুন।"});const session=await getSession(env.DB,env.SESSION_STORE,token);if(!session)return out(401,trace(request),null,{code:"SESSION_INVALID",message:"আপনার প্রশাসনিক সেশনটি আর বৈধ নয়।"});const u=await findUserById(env.DB,session.userId);if(!u||u.status!=="ACTIVE"||!u.personId)return out(403,trace(request),null,{code:"FORBIDDEN",message:"এই assignment-এর অনুমতি নেই।"});const p=await getUserPermissions(env.DB,u.id);if(!p.some(x=>x.code==="committee.manage"))return out(403,trace(request),null,{code:"FORBIDDEN",message:"টিকিট assign করার অনুমতি আপনার নেই।"});const current=await env.DB.prepare(`SELECT cra.person_id FROM committee_role_assignments cra JOIN committee_terms ct ON ct.id=cra.committee_term_id JOIN committees c ON c.id=ct.committee_id WHERE cra.person_id=? AND cra.status='ACTIVE' AND cra.committee_term_id=? AND c.id=? AND ct.status='ACTIVE' AND c.status='ACTIVE' AND cra.valid_from<=CURRENT_TIMESTAMP AND (cra.valid_to IS NULL OR cra.valid_to>=CURRENT_TIMESTAMP) LIMIT 1`).bind(u.personId,CANONICAL.currentCommitteeTermId,CANONICAL.committeeId).first<{person_id:string}>();if(!current)return out(403,trace(request),null,{code:"FORBIDDEN",message:"বর্তমান কমিটির সদস্যদের জন্যই assignment পরিবর্তন সংরক্ষিত।"});return {userId:u.id};}
export async function POST(request:Request):Promise<NextResponse>{const t=trace(request);const env=getCloudflareContext().env as unknown as Env;const principal=await auth(env,request);if(principal instanceof NextResponse)return principal;if(!env.DB)return out(503,t,null,{code:"DEPENDENCY_FAILURE",message:"Assignment ব্যবস্থা এখন প্রস্তুত নয়।"});const b=await parse(request);const ticketId=b?s(b.ticketId,128):null;const queue=b?s(b.queueCode,16)?.toUpperCase():null;const assignedUserId=b?.assignedUserId==null?null:s(b.assignedUserId,128);const assignedRoleId=b?.assignedRoleId==null?null:s(b.assignedRoleId,128);const expectedVersion=b&&typeof b.expectedVersion==="number"?b.expectedVersion:null;const reason=s(b?.reasonCode??"ASSIGNED",64)||"ASSIGNED";if(!b||!ticketId||!queue||expectedVersion===null||!Number.isSafeInteger(expectedVersion)||expectedVersion<1||(assignedUserId&&assignedRoleId)||(!assignedUserId&&!assignedRoleId)||!["FINANCE","PUJA","GOVERNANCE","GENERAL"].includes(queue))return out(400,t,null,{code:"INVALID_INPUT",message:"Assignment-এর তথ্য সঠিক নয়।"});try{const ticket=await env.DB.prepare("SELECT id,category_code,status,version FROM support_tickets WHERE id=? LIMIT 1").bind(ticketId).first<{id:string;category_code:string;status:string;version:number}>();if(!ticket)return out(404,t,null,{code:"NOT_FOUND",message:"টিকিটটি পাওয়া যায়নি।"});if(QUEUE_BY_CATEGORY[ticket.category_code]!==queue)return out(400,t,null,{code:"QUEUE_MISMATCH",message:"টিকিটের category-এর সঙ্গে routing queue মিলছে না।"});if(ticket.version!==expectedVersion)return out(409,t,null,{code:"STALE_VERSION",message:"টিকিটের assignment ইতিমধ্যে পরিবর্তিত হয়েছে।"});if(assignedUserId){const target=await env.DB.prepare(`SELECT cra.person_id FROM committee_role_assignments cra JOIN committee_terms ct ON ct.id=cra.committee_term_id JOIN committees c ON c.id=ct.committee_id JOIN users u ON u.person_id=cra.person_id WHERE u.id=? AND cra.status='ACTIVE' AND cra.committee_term_id=? AND c.id=? AND ct.status='ACTIVE' AND u.status='ACTIVE' AND cra.valid_from<=CURRENT_TIMESTAMP AND (cra.valid_to IS NULL OR cra.valid_to>=CURRENT_TIMESTAMP) LIMIT 1`).bind(assignedUserId,CANONICAL.currentCommitteeTermId,CANONICAL.committeeId).first();if(!target)return out(400,t,null,{code:"INVALID_ASSIGNEE",message:"নির্বাচিত user বর্তমান committee assignment-এর মধ্যে নেই।"});} else {const target=await env.DB.prepare(`SELECT cra.role_id FROM committee_role_assignments cra JOIN committee_terms ct ON ct.id=cra.committee_term_id JOIN committees c ON c.id=ct.committee_id WHERE cra.role_id=? AND cra.status='ACTIVE' AND cra.committee_term_id=? AND c.id=? AND ct.status='ACTIVE' LIMIT 1`).bind(assignedRoleId,CANONICAL.currentCommitteeTermId,CANONICAL.committeeId).first();if(!target)return out(400,t,null,{code:"INVALID_ROLE",message:"নির্বাচিত role বর্তমান committee assignment-এর মধ্যে নেই।"});}
 const now=new Date().toISOString();const close=env.DB.prepare("UPDATE support_assignments SET status='RELEASED',released_at=?,reason_code=?,revision_id=? WHERE ticket_id=? AND status='ACTIVE'").bind(now,reason,crypto.randomUUID(),ticketId);const add=env.DB.prepare("INSERT INTO support_assignments (id,ticket_id,queue_code,assigned_user_id,assigned_role_id,assigned_by_user_id,status,assigned_at,reason_code,revision_id) VALUES (?,?,?,?,?,?,?,?,?,?)").bind(crypto.randomUUID(),ticketId,queue,assignedUserId,assignedRoleId,principal.userId,"ACTIVE",now,reason,crypto.randomUUID());const ticketUpdate=env.DB.prepare("UPDATE support_tickets SET version=version+1,updated_at=? WHERE id=? AND version=?").bind(now,ticketId,expectedVersion);const auditKey=await sha256(`${principal.userId}:${ticketId}:${expectedVersion}:${queue}:${assignedUserId||assignedRoleId}`);const audit=env.DB.prepare("INSERT INTO support_audit_events (id,ticket_id,actor_user_id,action,entity_type,entity_id,after_json,reason_code,occurred_at,idempotency_key_hash,metadata_json) VALUES (?,?,?,?,?,?,?,?,?,?,?) ON CONFLICT(idempotency_key_hash) DO NOTHING").bind(crypto.randomUUID(),ticketId,principal.userId,"ASSIGNMENT_UPDATED","SUPPORT_ASSIGNMENT",ticketId,JSON.stringify({queueCode:queue,assignedUserId:assignedUserId||null,assignedRoleId:assignedRoleId||null}),reason,now,auditKey,JSON.stringify({requestId:t}));const result=await env.DB.batch([close,add,ticketUpdate,audit]) as Array<{meta?:{changes?:number}}>;if(Number(result?.[2]?.meta?.changes??0)!==1)return out(409,t,null,{code:"CONFLICT",message:"Assignment সংরক্ষণ করা যায়নি; ticket version বদলে গেছে।"});return out(200,t,{ticketId,queueCode:queue,assignedUserId,assignedRoleId,version:expectedVersion+1});}catch{return out(503,t,null,{code:"DEPENDENCY_FAILURE",message:"Assignment সংরক্ষণ করা যায়নি।"});}}
async function sha256(value:string){return Array.from(new Uint8Array(await crypto.subtle.digest("SHA-256",new TextEncoder().encode(value))),b=>b.toString(16).padStart(2,"0")).join("");}
