import { getCloudflareContext } from "@opennextjs/cloudflare";
import { NextResponse } from "next/server";
import { getSession } from "../../../../lib/files/auth/session";
import { findUserById, getUserPermissions } from "../../../../lib/files/auth/repository";
import type { AuthDatabase, AuthSessionStore } from "../../../../lib/files/auth/types";

export const runtime = "edge";
export const dynamic = "force-dynamic";

type Env = { DB?: AuthDatabase; SESSION_STORE?: AuthSessionStore; SESSION_COOKIE_NAME?: string; CACHE?: { delete(key:string):Promise<void> } };
const HEADERS={"Cache-Control":"no-store, max-age=0","Content-Type":"application/json; charset=utf-8","X-Content-Type-Options":"nosniff","Referrer-Policy":"no-referrer"};
const SAFE_PATHS=["/","/today","/temple","/temple/about","/temple/history","/temple/heritage","/temple/timeline","/temple/traditions","/temple/priests","/temple/committee","/temple/facilities","/panjika","/panjika/today","/festivals","/darshan","/media","/documents","/notices","/community","/contact","/faq","/assistant"];

function traceId(r:Request){const v=r.headers.get("x-request-id")?.trim();return v&&v.length<=128?v:crypto.randomUUID();}
function out(status:number,t:string,data:unknown,error?:{code:string;message:string}){return NextResponse.json(error?{ok:false,error,meta:{traceId:t}}:{ok:true,data,meta:{traceId:t}},{status,headers:HEADERS});}
function cookie(r:Request,n:string){const h=r.headers.get("cookie");if(!h)return null;const e=n.replace(/[.*+?^${}()|[\]\\]/g,"\\$&");const m=h.match(new RegExp(`(?:^|;\\s*)${e}=([^;]*)`));return m?.[1]?decodeURIComponent(m[1]):null;}
async function auth(r:Request):Promise<{env:Env;userId:string}|NextResponse>{const env=getCloudflareContext().env as unknown as Env;const t=traceId(r);if(!env.DB||!env.SESSION_STORE)return out(503,t,null,{code:"DEPENDENCY_FAILURE",message:"প্রশাসনিক সেবা এখন উপলব্ধ নয়।"});const s=cookie(r,env.SESSION_COOKIE_NAME||"raksha_kali_session");if(!s)return out(401,t,null,{code:"SESSION_INVALID",message:"প্রশাসনিক লগইন প্রয়োজন।"});try{const sess=await getSession(env.DB,env.SESSION_STORE,s);if(!sess)return out(401,t,null,{code:"SESSION_INVALID",message:"আপনার প্রশাসনিক সেশন আর বৈধ নয়।"});const u=await findUserById(env.DB,sess.userId);if(!u||u.status!=="ACTIVE"||!u.personId)return out(403,t,null,{code:"FORBIDDEN",message:"এই কাজের অনুমতি নেই।"});const p=await getUserPermissions(env.DB,u.id);if(!p.some(x=>x.code==="system.manage"))return out(403,t,null,{code:"FORBIDDEN",message:"cache revalidation-এর অনুমতি নেই।"});return {env,userId:u.id};}catch{return out(503,t,null,{code:"DEPENDENCY_FAILURE",message:"প্রশাসনিক অনুমতি যাচাই করা যায়নি।"});}}

type Body={paths?:unknown[];reason?:unknown;entityType?:unknown;entityId?:unknown;tags?:unknown[]};

export async function POST(request:Request):Promise<NextResponse>{const t=traceId(request);const principal=await auth(request);if(principal instanceof NextResponse)return principal;let body:Body;try{const raw=await request.text();if(new TextEncoder().encode(raw).byteLength>16384)throw new Error("BODY_TOO_LARGE");const parsed:unknown=JSON.parse(raw);if(!parsed||typeof parsed!=="object"||Array.isArray(parsed))throw new Error("INVALID_INPUT");body=parsed as Body;}catch{return out(400,t,null,{code:"INVALID_INPUT",message:"Revalidation request সঠিক নয়।"});}const paths=Array.isArray(body.paths)?body.paths.filter((p):p is string=>typeof p==="string").map(p=>p.trim()).filter(Boolean):[];const tags=Array.isArray(body.tags)?body.tags.filter((x):x is string=>typeof x==="string").map(x=>x.trim()).filter(x=>x.length>0&&x.length<=128):[];const reason=typeof body.reason==="string"?body.reason.trim().slice(0,240):"";if(!reason||(paths.length===0&&tags.length===0)||paths.length>30||tags.length>50)return out(400,t,null,{code:"INVALID_INPUT",message:"path/tag এবং reason দিতে হবে।"});for(const path of paths){if(!SAFE_PATHS.includes(path)&&!/^\/festivals\/[A-Za-z0-9_-]+(?:\/[0-9]{4})?$/.test(path)&&!/^\/documents\/[A-Za-z0-9_-]+$/.test(path)&&!/^\/music\/[A-Za-z0-9_-]+$/.test(path))return out(400,t,null,{code:"PATH_NOT_ALLOWED",message:"অননুমোদিত cache path দেওয়া হয়েছে।"});}try{const { revalidatePath, revalidateTag }=await import("next/cache");for(const path of paths)revalidatePath(path);for(const tag of tags)revalidateTag(tag);if(principal.env.CACHE){for(const path of paths)await principal.env.CACHE.delete(`path:${path}`);for(const tag of tags)await principal.env.CACHE.delete(`tag:${tag}`);}await principal.env.DB!.prepare(`INSERT INTO audit_logs (id,actor_user_id,action,entity_type,entity_id,result,reason_private,request_id,occurred_at,created_at) VALUES (?,?,?,?,?,?,?,?,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP)`).bind(crypto.randomUUID(),principal.userId,"REVALIDATE","CACHE","PUBLIC_READ_MODEL","SUCCESS",reason,t).run();return out(200,t,{paths,tags,reason,cacheStoreInvalidated:Boolean(principal.env.CACHE)});}catch{return out(503,t,null,{code:"REVALIDATE_FAILED",message:"Public cache revalidation সম্পন্ন করা যায়নি।"});}}
