import {
  scheduledHandler,
  type ExecutionContextLike,
  type ScheduledControllerLike,
} from "./scheduled";
import type { WorkerBindings } from "./bindings";

// The OpenNext adapter generates this module during `next build`.
// @ts-expect-error Generated by @opennextjs/cloudflare at build time.
import openNextWorker from "../.open-next/worker.js";

export interface WorkerExecutionContext extends ExecutionContextLike {}

interface OpenNextHandler {
  fetch(
    request: Request,
    env: WorkerBindings,
    ctx: WorkerExecutionContext,
  ): Promise<Response> | Response;
}

const application = openNextWorker as OpenNextHandler;

export default {
  fetch(
    request: Request,
    env: WorkerBindings,
    ctx: WorkerExecutionContext,
  ): Promise<Response> | Response {
    return application.fetch(request, env, ctx);
  },

  scheduled(
    controller: ScheduledControllerLike,
    env: WorkerBindings,
    ctx: WorkerExecutionContext,
  ): Promise<void> {
    return scheduledHandler(controller, env, ctx);
  },
};
