import { getCloudflareContext } from "@opennextjs/cloudflare";
import { NextResponse } from "next/server";
import { getSession } from "../../../../../lib/files/auth/session";
import { findUserById, getUserPermissions } from "../../../../../lib/files/auth/repository";
import type { AuthDatabase, AuthSessionStore } from "../../../../../lib/files/auth/types";

export const runtime = "edge";
export const dynamic = "force-dynamic";

const BODY_LIMIT = 10000;
const HEADERS = { "Cache-Control": "no-store, max-age=0", "Content-Type": "application/json; charset=utf-8", "X-Content-Type-Options": "nosniff", "Referrer-Policy": "no-referrer" };
type Env={DB?:AuthDatabase;SESSION_STORE?:AuthSessionStore;SESSION_COOKIE_NAME?:string};
type Body={ticketId?:unknown;note?:unknown};
function out(status:number,trace:string,data:unknown,error?:{code:string;message:string}){return NextResponse.json(error?{ok:false,error,meta:{traceId:trace}}:{ok:true,data,meta:{traceId:trace}},{status,headers:HEADERS});}
function trace(request:Request){const v=request.headers.get("x-request-id")?.trim();return v&&v.length<=128?v:crypto.randomUUID();}
async function parse(request:Request):Promise<Body|null>{const len=request.headers.get("content-length");if(len&&(!/^\d+$/.test(len)||Number(len)>BODY_LIMIT))return null;const raw=await request.text();if(new TextEncoder().encode(raw).byteLength>BODY_LIMIT)return null;try{const p:unknown=JSON.parse(raw);return p&&typeof p==="object"&&!Array.isArray(p)?p as Body:null;}catch{return null;}}
function text(v:unknown,max:number){if(typeof v!=="string")return null;const s=v.trim();return s&&s.length<=max?s:null;}
function cookie(request:Request,name:string){const h=request.headers.get("cookie");if(!h)return null;const x=h.split(";").map((v)=>v.trim()).find((v)=>v.startsWith(`${name}=`));return x?decodeURIComponent(x.slice(name.length+1)):null;}
async function principal(db:AuthDatabase,store:AuthSessionStore|undefined,request:Request,name:string){if(!store)return null;const token=cookie(request,name);if(!token)return null;const s=await getSession(db,store,token);if(!s)return null;const u=await findUserById(db,s.userId);if(!u||u.status!=="ACTIVE"||!u.personId)return null;const p=await getUserPermissions(db,u.id);return p.some((x)=>x.code==="support.note")?u.id:null;}
export async function POST(request:Request):Promise<NextResponse>{const traceId=trace(request);const runtime=getCloudflareContext().env as unknown as Env;if(!runtime.DB)return out(503,traceId,null,{code:"DEPENDENCY_FAILURE",message:"Internal note ব্যবস্থা এখন প্রস্তুত নয়।"});const body=await parse(request);const ticketId=body?text(body.ticketId,128):null;const note=body?text(body.note,20000):null;if(!ticketId||!note)return out(400,traceId,null,{code:"INVALID_INPUT",message:"টিকিট এবং internal note দুটিই দিতে হবে।"});try{const userId=await principal(runtime.DB,runtime.SESSION_STORE,request,runtime.SESSION_COOKIE_NAME?.trim()||"raksha_kali_session");if(!userId)return out(403,traceId,null,{code:"FORBIDDEN",message:"Internal note লেখার অনুমতি আপনার নেই।"});const ticket=await runtime.DB.prepare(`SELECT id,status FROM support_tickets WHERE id=? LIMIT 1`).bind(ticketId).first<{id:string;status:string}>();if(!ticket)return out(404,traceId,null,{code:"NOT_FOUND",message:"টিকিট পাওয়া যায়নি।"});if(ticket.status==="CLOSED")return out(409,traceId,null,{code:"INVALID_STATE",message:"বন্ধ টিকিটে internal note যোগ করা যাবে না।"});const noteId=crypto.randomUUID();const revision=crypto.randomUUID();const result=await runtime.DB.batch([runtime.DB.prepare(`INSERT INTO support_internal_notes(id,ticket_id,author_user_id,note_private,created_at,updated_at,revision_id) VALUES(?,?,?, ?,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,?)`).bind(noteId,ticketId,userId,note,revision),runtime.DB.prepare(`INSERT INTO support_audit_events(id,ticket_id,actor_user_id,action,entity_type,entity_id,after_json,reason_code,metadata_json) VALUES(?,?,?,'INTERNAL_NOTE_CREATE','SupportInternalNote',?, ?, 'SUPPORT_NOTE', ?)`).bind(crypto.randomUUID(),ticketId,userId,noteId,JSON.stringify({length:note.length,revisionId:revision}),JSON.stringify({traceId}))]);const changes=Number((result[0] as {meta?:{changes?:number}})?.meta?.changes??0);if(changes!==1)return out(409,traceId,null,{code:"WRITE_CONFLICT",message:"Internal note একই সময়ে পরিবর্তিত হয়েছে।"});return out(201,traceId,{noteId,visibility:"INTERNAL_NOTE",status:"STORED"});}catch{return out(500,traceId,null,{code:"INTERNAL_FAILURE",message:"Internal note এখন সংরক্ষণ করা যাচ্ছে না।"});}}
